stages:
  - build
  - deploy

build:
  stage: build
  image: iquiw/alpine-emacs
  before_script:
    - apk update && apk add make
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  image: python:latest
  variables:
    S3_BUCKET_NAME: "venikx.com"
  dependencies:
    - build
  before_script:
    - pip install awscli -q
  script:
    - aws s3 sync public s3://${S3_BUCKET_NAME}/ --recursive --delete
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
  only:
    - master
