variables:
  HUGO_VERSION: 0.65.3

stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: klakegg/hugo
    entrypoint: [""]
  before_script:
    - apk update && apk add make
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  image: node:12
  dependencies:
    - build
  before_script:
    - npm i -g netlify-cli
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master
