image: node:12.13.1

cache:
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: production
    url: https://venikx.com
  script:
    - npm i
    - npm run build
    - npm run publish
