image: node:12.13.1

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm install
  only:
    - master

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  dependencies:
    - build
  before_script:
    - npm i -g netlify-cli
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master
