stages:
  - build
  - deploy

build:
  stage: build
  image: iquiw/alpine-emacs
  before_script:
    - apk update && apk add make
  script:
    - make publish
  artifacts:
    paths:
      - public
  only:
    - master

deploy:
  stage: deploy
  image: node:12
  dependencies:
    - build
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  only:
    - master
