name: "Deploy to Netlify"
on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: sudo apt-get install make
    - uses: purcell/setup-emacs@master
      with:
        version: 27.2
    
    - run: make
    - uses: netlify/actions/cli@master
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      with:
        args: deploy --dir=public --prod
